---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ops
  name: alertmanager-sns-forwarder-config
data:
  alertmanager-sns-forwarder-config: |
    aws_region: "eu-central-1"
    sns_topics:
      - name: "TopicA"
        arn: "arn:aws:sns:us-east-1:123456789012:TopicA"
        start_time: "22:00"
        end_time: "16:00"
      - name: "TopicB"
        arn: "arn:aws:sns:us-east-1:123456789012:TopicB"
        start_time: "22:00"
        end_time: "16:00"
    alertnames:
      - "AlertName"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-sns-forwarder
  namespace: ops
  labels:
    app: alertmanager-sns-forwarder
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: alertmanager-sns-forwarder
  template:
    metadata:
      labels:
        app: alertmanager-sns-forwarder
      annotations:
        iam.amazonaws.com/role: sns-forwarder-role
    spec:
      containers:
        - name: alertmanager-sns-forwarder
          image: maks3201/alertmanager-sns-forwarder:0.0.7
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: alertmanager-sns-forwarder-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: alertmanager-sns-forwarder-secret
                  key: aws_secret_access_key
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: webhook-port
          livenessProbe:
            httpGet:
              path: /healthz
              port: webhook-port
            initialDelaySeconds: 30
            timeoutSeconds: 10
      volumes:
      - name: config
        configMap:
          name: alertmanager-sns-forwarder-config
          items:
          - key: "alertmanager-sns-forwarder-config"
            path: "config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-sns-forwarder
  namespace: ops
  labels:
    app: alertmanager-sns-forwarder
spec:
  selector:
    app: alertmanager-sns-forwarder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
