---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-sns-forwarder
  namespace: ops
  labels:
    app: alertmanager-sns-forwarder
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: alertmanager-sns-forwarder
  template:
    metadata:
      labels:
        app: alertmanager-sns-forwarder
      annotations:
        iam.amazonaws.com/role: sns-forwarder-role
    spec:
      restartPolicy: Always
      containers:
        - name: alertmanager-sns-forwarder
          image: maks3201/alertmanager-sns-forwarder:0.0.4
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              value: ""
            - name: SNS_TOPIC_ARN
              value: ""
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: alertmanager-sns-forwarder-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: alertmanager-sns-forwarder-secret
                  key: aws_secret_access_key
            - name: AWS_ACCOUNT_ID
              value: "517455315985"
            - name: ALERT_START_TIME
              value: "00:00"
            - name: ALERT_END_TIME
              value: "23:59"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-sns-forwarder
  namespace: ops
  labels:
    app: alertmanager-sns-forwarder
spec:
  selector:
    app: alertmanager-sns-forwarder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
