---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-sns-forwarder
  namespace: ops
  labels:
    app: alertmanager-sns-forwarder
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: alertmanager-sns-forwarder
  template:
    metadata:
      labels:
        app: alertmanager-sns-forwarder
      annotations:
        iam.amazonaws.com/role: sns-forwarder-role
    spec:
      restartPolicy: Always
      containers:
        - name: alertmanager-sns-forwarder
          image: maks3201/alertmanager-sns-forwarder:0.0.1
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              value: ""
            - name: SNS_TOPIC_ARN
              value: ""
            - name: AWS_ACCESS_KEY_ID
              value: ""
            - name: AWS_SECRET_ACCESS_KEY
              value: ""
            - name: AWS_ACCOUNT_ID
              value: ""
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
